# Generated by Django 3.2.10 on 2022-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_author_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='created_at',
        ),
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
